version: "3.8"

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IprGuardians
    ports:
      - "5436:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ipr
    restart: always
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_db:5432/IprGuardians?schema=public"
      NEXTAUTH_URL: "https://iprguardians.com/"
      NEXTAUTH_SECRET: "your-nextauth-secret-key-change-this-in-production"

    ports:
      - "5555:3000"
    command: ["/bin/sh", "-c", "npx prisma migrate deploy && npm run start"]

volumes:
  pg_data:
